@startuml seq

skinparam SequenceLifeLineBackgroundColor LightYellow

title "Game gets drawn"

participant "JVM" as jvm
participant "gameFrame: GameFrame" as gameFrame

jvm -> gameFrame ++: paintComponent()

gameFrame -> gameFrame ++: UpdateComponent()
deactivate gameFrame

gameFrame -> jvm --

@enduml