@startuml seq

skinparam SequenceLifeLineBackgroundColor LightYellow

title "Game gets drawn"

participant ": TurnController" as jvm
participant "gameFrame: GameFrame" as gameFrame

jvm -> gameFrame ++: UpdateComponent()

gameFrame -> jvm --

@enduml